spring:
  application:
    name: springDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
server:
  port: ${MYSQL_PORT}
jwt:
  base-key: ${JWT_HMAC_KEY}
  expiration-time: ${JWT_EXP_TIME}
  refresh-time: ${JWT_REF_TIME}